# Generated by Django 4.2 on 2023-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=20)),
                ('doctorid', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('token', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('patientid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('contact1', models.IntegerField()),
                ('emgnumber', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='addInfo',
        ),
    ]
