# Generated by Django 4.2 on 2023-04-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_booking_patientdetails_delete_addinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
