# Generated by Django 4.2 on 2023-04-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=20)),
                ('doctorid', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('token', models.IntegerField()),
            ],
        ),
    ]
